In [1]:
arr = [1,2,3,4]

In [2]:
print(arr)

[1, 2, 3, 4]

In [3]:
print("Hello world")

Hello world

In [4]:
import pandas as pd

In [6]:
dic1 = {"Movie":['Lord of the Rings','Pulp Fiction','Fight club'],"Year":['2000','1994','1998']}
df1= pd.DataFrame(dic1)
df1

               Movie  Year
0  Lord of the Rings  2000
1       Pulp Fiction  1994
2         Fight club  1998

In [11]:
dic2 = {"Movie":['Goodfellas','Inception','Brittanny runs a Marathon'],"Year":['1992','2004','2017']}
df2= pd.DataFrame(dic2)
df_combined= pd.concat([df1,df2])
df_combined

                       Movie  Year
0          Lord of the Rings  2000
1               Pulp Fiction  1994
2                 Fight club  1998
0                 Goodfellas  1992
1                  Inception  2004
2  Brittanny runs a Marathon  2017